services:
  - type: web
    name: tese-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn teseapp.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DJANGO_SETTINGS_MODULE
        value: teseapp.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 3